CITY_TO_IATA = {
    'ADAMPUR': 'AIP', 'AGARTALA': 'IXA', 'AGATTI ISLAND': 'AGX', 'AGRA': 'AGR', 'AHMEDABAD': 'AMD',
    'AIZAWL': 'AJL', 'ALIGARH AIRPORT': 'HRH', 'AMBIKAPUR AIRPORT': 'REU', 'AMRITSAR': 'ATQ', 'AURANGABAD': 'IXU',
    'AYODHYA INTERNATIONAL AIRPORT': 'AYJ', 'AZAMGARH AIRPORT': 'AZH', 'BAGDOGRA': 'IXB', 'BAREILLY': 'BEK', 'BELGAUM': 'IXG',
    'BENGALURU': 'BLR', 'BHATINDA': 'BUP', 'BHAVNAGAR': 'BHU', 'BHOPAL': 'BHO', 'BHUBANESWAR': 'BBI',
    'BHUJ': 'BHJ', 'BIKANER': 'BKB', 'BILASPUR': 'PAB', 'CHANDIGARH': 'IXC', 'CHENNAI': 'MAA', 'CHITRAKOOT AIRPORT': 'CWK',
    'COIMBATORE': 'CJB', 'COOCH BEHAR': 'COH', 'CUDDAPAH': 'CDP', 'DABOLIM': 'GOI', 'DARBHANGA': 'DBR',
    'DEHRADUN': 'DED', 'DELHI': 'DEL', 'DEOGHAR': 'DGH', 'DHARAMSALA': 'DHM', 'DIBRUGARH': 'DIB',
    'DIMAPUR': 'DMU', 'DIU': 'DIU', 'DURGAPUR': 'RDP', 'GAYA': 'GAY', 'GOA': 'GOX', 'GONDIA': 'GDB',
    'GORAKHPUR': 'GOP', 'GUWAHATI': 'GAU', 'GWALIOR': 'GWL', 'HINDON AIRPORT': 'HDO', 'HUBLI': 'HBX',
    'HYDERABAD': 'HYD', 'IMPHAL': 'IMF', 'INDORE': 'IDR', 'ITANAGAR': 'HGI', 'JABALPUR': 'JLR',
    'JAGDALPUR': 'JGB', 'JAIPUR': 'JAI', 'JAISALMER': 'JSA', 'JALGAON': 'JLG', 'JAMMU': 'IXJ',
    'JAMNAGAR': 'JGA', 'JAMSHEDPUR': 'IXW', 'JEYPORE': 'PYB', 'JHARSUGUDA': 'JRG', 'JODHPUR': 'JDH',
    'JORHAT': 'JRH', 'KALABURAGI': 'GBI', 'KANDLA': 'IXY', 'KANNUR': 'CNN', 'KANPUR': 'KNU', 'KESHOD': 'IXK',
    'KHAJURAHO': 'HJR', 'KISHANGARH': 'KQH', 'KOCHI': 'COK', 'KOLHAPUR': 'KLH', 'KOLKATA': 'CCU',
    'KOZHIKODE': 'CCJ', 'KULLU': 'KUU', 'KURNOOL': 'KJB', 'LEH': 'IXL', 'LILABARI': 'IXI',
    'LUCKNOW': 'LKO', 'LUDHIANA': 'LUH', 'MADURAI': 'IXM', 'MALVAN': 'SDW', 'MANGALORE': 'IXE',
    'MORADABAD AIRPORT': 'MZS', 'MUMBAI': 'BOM', 'MYSORE': 'MYQ', 'NAGPUR': 'NAG', 'NANDED': 'NDC', 'NASIK': 'ISK', 'PAKYONG': 'PYG',
    'PANTNAGAR': 'PGH', 'PASIGHAT': 'IXT', 'PATNA': 'PAT', 'PITHORAGARH': 'NNS', 'PONDICHERRY': 'PNY',
    'PORBANDAR': 'PBD', 'PORT BLAIR': 'IXZ', 'PRAYAGRAJ': 'IXD', 'PUNE': 'PNQ', 'RAIPUR': 'RPR',
    'RAJAHMUNDRY': 'RJA', 'RAJKOT INTERNATIONAL AIRPORT': 'HSR', 'RANCHI': 'IXR', 'REWA': 'REW', 'ROURKELA': 'RRK',
    'RUPSI': 'RUP', 'SALEM': 'SXV', 'SHILLONG': 'SHL', 'SHIRDI': 'SAG', 'SHIVAMOGGA AIRPORT': 'RQY',
    'SHRAVASTI AIRPORT': 'VSV', 'SILCHAR': 'IXS', 'SIMLA': 'SLV', 'SRINAGAR': 'SXR', 'SURAT': 'STV',
    'TEZPUR': 'TEZ', 'TEZU': 'TEI', 'TIRUCHIRAPALLY': 'TRZ', 'TIRUPATI': 'TIR', 'TRIVANDRUM': 'TRV',
    'TUTICORIN': 'TCR', 'UDAIPUR': 'UDR', 'UTKELA': 'UKE', 'VADODARA': 'BDQ', 'VARANASI': 'VNS',
    'VIDYANAGAR': 'VDY', 'VIJAYAWADA': 'VGA', 'VISAKHAPATNAM': 'VTZ', 'ZIRO': 'ZER'
}

# Reverse map, title-cased for use in URLs (e.g. "DELHI" -> "Delhi") -
# EaseMyTrip's srch param wants city names, not just IATA codes.
IATA_TO_CITY = {code: city.title() for city, code in CITY_TO_IATA.items()}